(define (foo n)
  (let ((x 100))
    (if (> n 0)
	(begin (display x)
	       (newline)
	       (set! x (+ x 1))
	       (foo (- n 1)))
	false)))

(define (foo2 n)
  ((lambda (x)
    (if (> n 0)
	(begin (display x)
	       (newline)
	       (set! x (+ x 1))
	       (foo2 (- n 1)))))
   100))